export const doc = {
  id: "RC-CV-2026.06",
  rev: "2026.06",
  revisionDate: "20 JUN 2026",
  classification: "CONTROLLED",
  class: "CLASS A — PUBLIC",
  drawnBy: "R. CORRÊA",
  sheet: "1 OF 1",
  status: "ACTIVE",
};

export const resume = {
  name: "Rodrigo Corrêa",
  role: ".NET Developer",
  location: "Itajaí, SC — Brasil",
  region: "LATAM · GMT-3",
  email: "rodrigo@correa.dev",
  phone: "+55 47 98848-7414",
  linkedin: "https://www.linkedin.com/in/rodrigoitj/",
  domain: "correa.dev",
  yearsActive: "20+",
  availability: "OPEN TO OPPORTUNITIES",
  summary:
    "A Developer with twenty years building transactional systems and intranet portals for enterprise clients. Stack centered on the .NET platform with C#, Entity Framework, REST services, and SQL Server/Oracle/Postgres backends. Strong practice in clean code, SOLID, TDD, and CI/CD on Azure. Currently embedded with one of the largest companies in the world, Microsoft, via Wipro.",
  stack: {
    Languages: [".NET / C#", "JavaScript", "TypeScript", "PHP", "SQL"],
    "Frameworks / Runtimes": [
      ".NET Core",
      ".NET Framework",
      "Entity Framework",
      "Node.js",
      "React",
      "jQuery",
      "Yii2",
      "ColdFusion",
    ],
    "Data & Messaging": [
      "SQL Server",
      "Oracle",
      "Postgres",
      "MySQL",
      "MongoDB",
      "RabbitMQ",
      "Redis",
    ],
    "Infra & Delivery": [
      "Docker",
      "Kubernetes",
      "Azure Cloud",
      "CI/CD",
      "Microservices",
      "Git",
    ],
    "Practice": ["SOLID", "Clean Code", "TDD / xUnit", "Design Patterns", "Scrum"],
  },
  experience: [
    {
      company: "WIPRO",
      client: "Microsoft",
      role: "SR. C# Developer",
      period: "2018.10 — PRESENT",
      tenure: "",
      location: "Barueri, SP",
      mode: "Outsourced · Remote",
      env: [".NET Core", "C#", "EF", "SQL Server", "Azure", "Docker"],
      bullets: [
        "Working as a contractor for Microsoft, I collaborate with global teams to support and improve critical Microsoft Azure infrastructure. My role is focused on building reliable solutions that enhance service quality and streamline cloud provisioning through automation.",
        "In an Agile/Scrum environment, I actively participate in recurring standups and use Azure DevOps for planning, source control, CI/CD pipelines, testing, and release management, helping drive efficient collaboration and high-quality software delivery.",
      ],
    },
    {
      company: "QUAY",
      client: "Equatorial Energia",
      role: "Full Stack Developer",
      period: "2018.10 — 2026.02",
      tenure: "7 yr 9 mo",
      location: "Itajaí, SC",
      mode: "Outsourced · Remote",
      env: [".NET Core", "C#", "EF", "SQL Server", "Azure", "Docker"],
      bullets: [
        "Implement and maintain intranet portals and operational systems for Equatorial, the largest power distribution operator in Brazil (60M+ customers).",
        "Design and ship RESTful APIs, background workers, and integration layers against legacy and modern backends.",
        "Drive code quality through TDD, code review, and architectural standards across the squad.",
      ],
    },
    {
      company: "GRUPOW",
      role: "Backend Developer",
      period: "2013.04 — 2018.09",
      tenure: "5 yr 6 mo",
      location: "Itajaí, SC",
      mode: "On-site",
      env: ["PHP 5/7", "Yii2", "ColdFusion", "MySQL", "jQuery"],
      bullets: [
        "Built backend systems and web applications for major brands: Mondelez, Pepsico, Microsoft, Beto Carrero.",
        "Owned full feature lifecycle: data modeling, business logic, REST endpoints, and front-end integration.",
      ],
    },
    {
      company: "Arroba Design",
      role: "Full Stack Developer",
      period: "2011.01 — 2013.03",
      tenure: "2 yr 3 mo",
      location: "Itajaí, SC",
      mode: "On-site",
      env: ["PHP", "JavaScript", "MySQL", "HTML/CSS"],
      bullets: [
        "Delivered websites and web applications across multiple client engagements.",
        "Introduced the team to reusable components, design patterns, and source control workflow.",
      ],
    },
    {
      company: "Freelancer",
      role: "Full Stack Developer",
      period: "2008.12 — 2010.12",
      tenure: "2 yr 1 mo",
      location: "Itajaí, SC",
      mode: "Independent",
      env: ["PHP", "JavaScript", "MySQL", "E-commerce platforms"],
      bullets: [
        "Delivered websites, web applications, and e-commerce solutions for varied regional clients.",
      ],
    },
  ],
  education: [
    {
      school: "UNIGRANET",
      degree: "B.Sc. Systems Analysis and Development",
      period: "2018.04 — 2020.12",
      location: "Itajaí, SC",
      status: "CONCLUDED",
    },
  ],
  languages: [
    { name: "Portuguese", code: "PT-BR", level: "Native", cefr: "C2" },
    { name: "English", code: "EN-US", level: "Advanced", cefr: "C1" },
  ],
};