export const content = {
  en: {
    doc: {
      id: "RC-CV-2026.06",
      rev: "2026.06",
      revisionDate: "20 JUN 2026",
      classification: "CONTROLLED",
      class: "CLASS A — PUBLIC",
      drawnBy: "R. CORRÊA",
      sheet: "1 OF 1",
      status: "ACTIVE",
    },
    resume: {
      name: "Rodrigo Corrêa",
      role: ".NET Developer",
      location: "Itajaí, SC — Brasil",
      region: "LATAM · GMT-3",
      email: "rodrigo@correa.dev",
      phone: "+55 47 98848-7414",
      linkedin: "https://www.linkedin.com/in/rodrigoitj/",
      domain: "correa.dev",
      yearsActive: "20+",
      availability: "OPEN TO OPPORTUNITIES",
      summary:
        "A Developer with twenty years building transactional systems and intranet portals for enterprise clients. Stack centered on the .NET platform with C#, Entity Framework, REST services, and SQL Server/Oracle/Postgres backends. Strong practice in clean code, SOLID, TDD, and CI/CD on Azure. Currently embedded with one of the largest companies in the world, Microsoft, via Wipro.",
      stack: {
        Languages: [".NET / C#", "JavaScript", "TypeScript", "PHP", "SQL"],
        "Frameworks / Runtimes": [
          ".NET Core",
          ".NET Framework",
          "Entity Framework",
          "Node.js",
          "React",
          "jQuery",
          "Yii2",
          "ColdFusion",
        ],
        "Data & Messaging": [
          "SQL Server",
          "Oracle",
          "Postgres",
          "MySQL",
          "MongoDB",
          "RabbitMQ",
          "Redis",
        ],
        "Infra & Delivery": [
          "Docker",
          "Kubernetes",
          "Azure Cloud",
          "CI/CD",
          "Microservices",
          "Git",
        ],
        Practice: ["SOLID", "Clean Code", "TDD / xUnit", "Design Patterns", "Scrum"],
      },
      experience: [
        {
          company: "WIPRO",
          client: "Microsoft",
          role: "SR. C# Developer",
          period: "2018.10 — PRESENT",
          tenure: "",
          location: "Barueri, SP",
          mode: "Outsourced · Remote",
          env: [".NET Core", "C#", "EF", "SQL Server", "Azure", "Docker"],
          bullets: [
            "Working as a contractor for Microsoft, I collaborate with global teams to support and improve critical Microsoft Azure infrastructure. My role is focused on building reliable solutions that enhance service quality and streamline cloud provisioning through automation.",
            "In an Agile/Scrum environment, I actively participate in recurring standups and use Azure DevOps for planning, source control, CI/CD pipelines, testing, and release management, helping drive efficient collaboration and high-quality software delivery.",
          ],
        },
        {
          company: "QUAY",
          client: "Equatorial Energia",
          role: "Full Stack Developer",
          period: "2018.10 — 2026.02",
          tenure: "7 yr 9 mo",
          location: "Itajaí, SC",
          mode: "Outsourced · Remote",
          env: [".NET Core", "C#", "EF", "SQL Server", "Azure", "Docker"],
          bullets: [
            "Implement and maintain intranet portals and operational systems for Equatorial, the largest power distribution operator in Brazil (60M+ customers).",
            "Design and ship RESTful APIs, background workers, and integration layers against legacy and modern backends.",
            "Drive code quality through TDD, code review, and architectural standards across the squad.",
          ],
        },
        {
          company: "GRUPOW",
          role: "Backend Developer",
          period: "2013.04 — 2018.09",
          tenure: "5 yr 6 mo",
          location: "Itajaí, SC",
          mode: "On-site",
          env: ["PHP 5/7", "Yii2", "ColdFusion", "MySQL", "jQuery"],
          bullets: [
            "Built backend systems and web applications for major brands: Mondelez, Pepsico, Microsoft, Beto Carrero.",
            "Owned full feature lifecycle: data modeling, business logic, REST endpoints, and front-end integration.",
          ],
        },
        {
          company: "Arroba Design",
          role: "Full Stack Developer",
          period: "2011.01 — 2013.03",
          tenure: "2 yr 3 mo",
          location: "Itajaí, SC",
          mode: "On-site",
          env: ["PHP", "JavaScript", "MySQL", "HTML/CSS"],
          bullets: [
            "Delivered websites and web applications across multiple client engagements.",
            "Introduced the team to reusable components, design patterns, and source control workflow.",
          ],
        },
        {
          company: "Freelancer",
          role: "Full Stack Developer",
          period: "2008.12 — 2010.12",
          tenure: "2 yr 1 mo",
          location: "Itajaí, SC",
          mode: "Independent",
          env: ["PHP", "JavaScript", "MySQL", "E-commerce platforms"],
          bullets: [
            "Delivered websites, web applications, and e-commerce solutions for varied regional clients.",
          ],
        },
      ],
      education: [
        {
          school: "UNIGRANET",
          degree: "B.Sc. Systems Analysis and Development",
          period: "2018.04 — 2020.12",
          location: "Itajaí, SC",
          status: "CONCLUDED",
        },
      ],
      languages: [
        { name: "Portuguese", code: "PT-BR", level: "Native", cefr: "C2" },
        { name: "English", code: "EN-US", level: "Advanced", cefr: "C1" },
      ],
    },
    ui: {
      documentType: "TECHNICAL RECORD",
      rev: "REV",
      sheet: "SHEET",
      roleLine: "Full Stack Developer · .NET · Azure",
      abstract: "§0 · Abstract",
      sections: {
        stack: { num: "§01", crumb: "Stack & Practice", title: "Technical Stack" },
        experience: {
          num: "§02",
          crumb: "Operational Record",
          title: "Professional Experience",
        },
        education: { num: "§03", crumb: "Academic Record", title: "Education" },
        languages: { num: "§04", crumb: "Working Languages", title: "Languages" },
        contact: { num: "§05", crumb: "Point of Contact", title: "Contact" },
      },
      titleBlock: {
        subject: "Subject",
        discipline: "Discipline",
        yearsActive: "Years Active",
        domain: "Domain",
      },
      contact: {
        email: "Electronic Mail",
        phone: "Telephony",
        network: "Professional Network",
        region: "Region / Time Zone",
      },
      endBlock: {
        drawnBy: "Drawn By",
        revision: "Revision",
        documentId: "Document ID",
        status: "Status",
      },
      via: "via",
      cefr: "CEFR",
      themeToggle: {
        toLight: "Switch to light theme",
        toDark: "Switch to dark theme",
      },
      langToggle: "Switch language to Portuguese",
    },
  },
  "pt-br": {
    doc: {
      id: "RC-CV-2026.06",
      rev: "2026.06",
      revisionDate: "20 JUN 2026",
      classification: "CONTROLADO",
      class: "CLASSE A — PÚBLICO",
      drawnBy: "R. CORRÊA",
      sheet: "1 DE 1",
      status: "ATIVO",
    },
    resume: {
      name: "Rodrigo Corrêa",
      role: "Desenvolvedor .NET",
      location: "Itajaí, SC — Brasil",
      region: "LATAM · GMT-3",
      email: "rodrigo@correa.dev",
      phone: "+55 47 98848-7414",
      linkedin: "https://www.linkedin.com/in/rodrigoitj/",
      domain: "correa.dev",
      yearsActive: "20+",
      availability: "ABERTO A OPORTUNIDADES",
      summary:
        "Desenvolvedor com vinte anos de experiência construindo sistemas transacionais e portais de intranet para clientes corporativos. Stack centrado na plataforma .NET com C#, Entity Framework, serviços REST e bancos de dados SQL Server/Oracle/Postgres. Forte prática em clean code, SOLID, TDD e CI/CD no Azure. Atualmente atuando em uma das maiores empresas do mundo, a Microsoft, via Wipro.",
      stack: {
        Linguagens: [".NET / C#", "JavaScript", "TypeScript", "PHP", "SQL"],
        "Frameworks / Ambientes": [
          ".NET Core",
          ".NET Framework",
          "Entity Framework",
          "Node.js",
          "React",
          "jQuery",
          "Yii2",
          "ColdFusion",
        ],
        "Dados & Mensageria": [
          "SQL Server",
          "Oracle",
          "Postgres",
          "MySQL",
          "MongoDB",
          "RabbitMQ",
          "Redis",
        ],
        "Infra & Entrega": [
          "Docker",
          "Kubernetes",
          "Azure Cloud",
          "CI/CD",
          "Microsserviços",
          "Git",
        ],
        Práticas: ["SOLID", "Clean Code", "TDD / xUnit", "Design Patterns", "Scrum"],
      },
      experience: [
        {
          company: "WIPRO",
          client: "Microsoft",
          role: "Desenvolvedor C# Sênior",
          period: "2018.10 — ATUAL",
          tenure: "",
          location: "Barueri, SP",
          mode: "Terceirizado · Remoto",
          env: [".NET Core", "C#", "EF", "SQL Server", "Azure", "Docker"],
          bullets: [
            "Atuando como contratado pela Microsoft, colaboro com equipes globais para dar suporte e melhorar a infraestrutura crítica do Microsoft Azure. Meu papel é focado em construir soluções confiáveis que aumentam a qualidade do serviço e simplificam o provisionamento em nuvem por meio de automação.",
            "Em um ambiente Ágil/Scrum, participo ativamente de reuniões diárias e uso o Azure DevOps para planejamento, controle de versão, pipelines de CI/CD, testes e gestão de releases, ajudando a impulsionar uma colaboração eficiente e entregas de software de alta qualidade.",
          ],
        },
        {
          company: "QUAY",
          client: "Equatorial Energia",
          role: "Desenvolvedor Full Stack",
          period: "2018.10 — 2026.02",
          tenure: "7 anos e 9 meses",
          location: "Itajaí, SC",
          mode: "Terceirizado · Remoto",
          env: [".NET Core", "C#", "EF", "SQL Server", "Azure", "Docker"],
          bullets: [
            "Implemento e mantenho portais de intranet e sistemas operacionais para a Equatorial, a maior distribuidora de energia elétrica do Brasil (mais de 60 milhões de clientes).",
            "Projeto e entrego APIs RESTful, workers em background e camadas de integração com backends legados e modernos.",
            "Impulsiono a qualidade de código por meio de TDD, code review e padrões arquiteturais em todo o squad.",
          ],
        },
        {
          company: "GRUPOW",
          role: "Desenvolvedor Backend",
          period: "2013.04 — 2018.09",
          tenure: "5 anos e 6 meses",
          location: "Itajaí, SC",
          mode: "Presencial",
          env: ["PHP 5/7", "Yii2", "ColdFusion", "MySQL", "jQuery"],
          bullets: [
            "Desenvolvi sistemas backend e aplicações web para grandes marcas: Mondelez, Pepsico, Microsoft, Beto Carrero.",
            "Responsável pelo ciclo de vida completo de features: modelagem de dados, regras de negócio, endpoints REST e integração front-end.",
          ],
        },
        {
          company: "Arroba Design",
          role: "Desenvolvedor Full Stack",
          period: "2011.01 — 2013.03",
          tenure: "2 anos e 3 meses",
          location: "Itajaí, SC",
          mode: "Presencial",
          env: ["PHP", "JavaScript", "MySQL", "HTML/CSS"],
          bullets: [
            "Entreguei websites e aplicações web em diversos projetos de clientes.",
            "Introduzi a equipe a componentes reutilizáveis, design patterns e fluxo de controle de versão.",
          ],
        },
        {
          company: "Freelancer",
          role: "Desenvolvedor Full Stack",
          period: "2008.12 — 2010.12",
          tenure: "2 anos e 1 mês",
          location: "Itajaí, SC",
          mode: "Autônomo",
          env: ["PHP", "JavaScript", "MySQL", "Plataformas de e-commerce"],
          bullets: [
            "Entreguei websites, aplicações web e soluções de e-commerce para diversos clientes regionais.",
          ],
        },
      ],
      education: [
        {
          school: "UNIGRANET",
          degree: "Bacharelado em Análise e Desenvolvimento de Sistemas",
          period: "2018.04 — 2020.12",
          location: "Itajaí, SC",
          status: "CONCLUÍDO",
        },
      ],
      languages: [
        { name: "Português", code: "PT-BR", level: "Nativo", cefr: "C2" },
        { name: "Inglês", code: "EN-US", level: "Avançado", cefr: "C1" },
      ],
    },
    ui: {
      documentType: "REGISTRO TÉCNICO",
      rev: "REV",
      sheet: "FOLHA",
      roleLine: "Desenvolvedor Full Stack · .NET · Azure",
      abstract: "§0 · Resumo",
      sections: {
        stack: { num: "§01", crumb: "Stack & Prática", title: "Stack Técnico" },
        experience: {
          num: "§02",
          crumb: "Registro Operacional",
          title: "Experiência Profissional",
        },
        education: { num: "§03", crumb: "Registro Acadêmico", title: "Formação" },
        languages: { num: "§04", crumb: "Idiomas de Trabalho", title: "Idiomas" },
        contact: { num: "§05", crumb: "Ponto de Contato", title: "Contato" },
      },
      titleBlock: {
        subject: "Assunto",
        discipline: "Disciplina",
        yearsActive: "Anos Ativo",
        domain: "Domínio",
      },
      contact: {
        email: "Correio Eletrônico",
        phone: "Telefonia",
        network: "Rede Profissional",
        region: "Região / Fuso Horário",
      },
      endBlock: {
        drawnBy: "Elaborado Por",
        revision: "Revisão",
        documentId: "ID do Documento",
        status: "Status",
      },
      via: "via",
      cefr: "CEFR",
      themeToggle: {
        toLight: "Mudar para tema claro",
        toDark: "Mudar para tema escuro",
      },
      langToggle: "Switch language to English",
    },
  },
};